# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e8cf5fd14b4c0b1476138a3b4f749d45"
name = "vip-pricing-app"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_products,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
  "https://example.com/api/auth/callback"
]
